name: Various PHP Install

on:
    push:
        branches:
            - main

jobs:
    code_analysis:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                actions:
                    php:
                        - 7.2
                        - 8.0
                        - 8.1

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            # composer install cache - https://github.com/ramsey/composer-install
            -   run: composer require tomasvotruba/type-coverage --dev --ansi
